Wsl compatibility
treee111/wahooMapsCreator pull request #72
Opened 2021-11-14 16:56 UTC by Ebe66

**Thank you for your contribution!** 🙌

To get it merged faster, please use this template and replace as many "{...}" as possible and kindly review the checklist below.

## This PR…

a simple, one sentence summary of the ticket ensures the PR has a clear overall focus.

{Prevents the initialisation of the graphical GUI on  WSL.}

## Considerations and implementations

This is the main body of the PR, and varies massively by PR. A simple PR may have a single sentence here, others may have multiple paragraphs, diagrams, etc.

{...}

## Pull Request Checklist
- [ ] Reviewed the [Contributing Guidelines](https://github.com/treee111/wahooMapsCreator/blob/develop/.github/CONTRIBUTING.md)
    + Especially the [Pull-Requests](https://github.com/treee111/wahooMapsCreator/blob/develop/.github/CONTRIBUTING.md#Pull-Requests) section
- [ ] commits (and commit-messages) are understandable
- [ ] {...}

2021-11-14 22:29 UTC, treee111 requested changes
thanks for this PR! 👍 
you nicely spotted a wrong thing here in my opinion!
The inititalization of the GUI should not happen always. That should happen only if in GUI mode (and then, a GUI and tk is available)

I added a inline-comment to a possible other solution to takkle that.

2021-11-14 22:29 UTC, treee111 commented on common_python/input.py
>          tk.Tk.__init__(self, *args, **kwargs)
would it help to move lines 64 until 83 into the if-statement after line 54?
line 58 needs then to be the first line of this init-function

Or even move lines 66 until 83 into the start_gui() function and leave 64 in the if-statement after line 54?

for macOS that seams to work. I wonder if it also works on WSL?

2021-11-14 23:39 UTC, treee111 commented on common_python/input.py
>          tk.Tk.__init__(self, *args, **kwargs)
as discussed, this is an other topic which is tackled in #73. this here is good to go! 💯

2021-11-14 23:45 UTC, treee111 approved these changes

2021-11-14 23:45 UTC, merged

2023-05-03 11:06 UTC, mbrieske commented
May I ask what bug this PR actually fixes? I work mainly on Ubuntu inside WSL for most of my programming stuff, and after installing wahoomc when I first wanted to start the Gui the error "no display found" drove me crazy. That is, until I found out about this "bugfix"... removed it, and now everything is working fine.

2023-05-03 11:28 UTC, Ebe66 commented
Hope Treee111 does not mind me trying to answer this.

At the time of this PR wsl did not, to our knowledge, have support for graphical interfaces. So a check was added to see if we where running on wsl and if so abort the gui.
It appears the graphical interface was added in the mean time. I'm watching a youtube on it now.    
@treee111 maybe we can do some testing and (re)add it. Maybe it is possible to check the wsl version used?